version: "3.8"
services:

  fastapi:
    container_name: fastapi
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.dev
    depends_on:
      - postgres
    volumes:
        - ./src:/opt/src
    networks:
      - reinigungsservice_network
    ports:
      - "8000:8000"
    command: [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload" ]

  postgres:
    container_name: postgres
    image: postgres:12.19-alpine
    env_file:
      - .env.dev
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - reinigungsservice_network

networks:
  reinigungsservice_network:
    driver: bridge
