"""Create user table

Revision ID: 3f4159fff59e
Revises: 10f99a06f499
Create Date: 2025-07-24 07:44:05.070920

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '3f4159fff59e'
down_revision: Union[str, Sequence[str], None] = '10f99a06f499'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
