"""empty message

Revision ID: 639c21097b94
Revises: 3f4159fff59e
Create Date: 2025-07-28 11:07:23.968199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '639c21097b94'
down_revision: Union[str, Sequence[str], None] = '3f4159fff59e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'code',
               existing_type=sa.VARCHAR(length=2),
               type_=sa.String(length=3),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'code',
               existing_type=sa.String(length=3),
               type_=sa.VARCHAR(length=2),
               existing_nullable=False)
    # ### end Alembic commands ###
